### ISSUE TITLE
Output to File (CSV)

### ISSUE THREAD

**Issue by jgamblin** [mprpic/cvelint#1]
This is a great tool, but would it be possible to add an option to output to CSV?  I was looking to see the most popular rule violations, and there are more than was expected just looking at this year. 

![Screenshot 2023-09-06 at 1 42 52 PM](https://github.com/mprpic/cvelint/assets/8428124/25aba374-5b83-4ec8-8a45-05b9e8e7983e)

**Comment by mprpic** [comment]
@jgamblin Yea, you can output to both JSON and CSV as a complement to the default text output:

```
./cvelint -format csv <path>
```

Both CSV and JSON contain a bit more data (path of the element that violates a rule and the name of the check) than the text output.

The most common error will be the trailing space found in most CVE records produced by Vulnogram because of this issue: https://github.com/Vulnogram/Vulnogram/issues/128

Duplicate refs are also fairly common, which was a bit of a surprise actually.

**Comment by jgamblin** [comment]
Thanks! That is perfect.
